import React from 'react'
import Head from 'next/head'
import styles from '../styles/About.module.css'
import { ImYoutube2, ImFacebook2 } from 'react-icons/im'
import { TiSocialInstagram } from 'react-icons/ti'
import Link from 'next/link'

export default function About() {

    const youtubeChannel = () => {
        document.location.href = 'https://stackoverflow.com/';
      }

      const instgramHandle = () => {
        document.location.href = 'https://stackoverflow.com/';
      }

      const facebookPage = () => {
        document.location.href = 'https://stackoverflow.com/';
      }

    return (
        
        <>
        <Head>
        <title>CarPotal | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <main className={styles.main_about}>
                <h2>About Us</h2>
                <p>Founded in 2020, The car portal is a space that talks about cars, a space where you find anything about cars and car related stuff Started as an Instagram blog, expanding the horizon to car sales, fun YouTube videos, cool car merch</p>
                <div className={styles.social__links}>
                    <div className={styles.single_link} style={{background: '#fd00008e'}} onClick={youtubeChannel}>
                        <div className={styles.icon}>
                            <ImYoutube2 />
                        </div>
                        <div className={styles.text}>
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsam, saepe.
                        </div>
                    </div>
                    <div className={styles.single_link} style={{background: '#a0d831a2'}}> 
                        <div className={styles.icon}>
                            <TiSocialInstagram />
                        </div>
                        <div className={styles.text}>
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsam, saepe.
                        </div>
                    </div>
                    <div className={styles.single_link} style={{background: '#ffff0091'}}>
                        <div className={styles.icon}>
                            <ImFacebook2 style={{fontSize: '40px'}}/>
                        </div>
                        <div className={styles.text}>
                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsam, saepe.
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}
