import React from 'react'
import Head from 'next/head'
import styles from '../styles/Affiliate.module.css'

function Affiliate() {
    return (
        <div>
          <Head>
            <title>CarPotal | Affiliates</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.affiliate__body}>
            <h2>Watch this space for all our affiliate partners</h2>
          </div>
        </div>
    )
}

export default Affiliate
