import React from "react";
import Head from "next/head";
import styles from "../styles/Carsales.module.css";
import axios from "axios";
import { getNumberWithCommas } from "../utils/functions";
import Link from "next/link";

function Carsales({ martInfo }) {
  console.log(martInfo);

  return (
    <div>
      <Head>
        <title>CarPotal | Car sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.auto_mart}>
        <aside className={styles.mart_side}>
          <div className={styles.mart_menu}>
            <ul>
              <li className={styles.menu_head}>CLASS</li>
              <li>Sedan</li>
              <li>Suv</li>
              <li>Truck</li>
              <li>Sedan</li>
            </ul>
          </div>
        </aside>
        <section className={styles.mart_body}>
          {martInfo.map((item, i) => (
            <Link href={`/carsales/${item.id}`} key={i}>
              <a className={styles.mart_item}>
                <div className={styles.item_info}>
                  <div className={styles.image}>
                    <img src={item.images[0]} alt="" />
                  </div>
                  <h4>{item.name}</h4>
                  <h2>
                    {"\u20A6"}
                    {getNumberWithCommas(item.price)}
                  </h2>
                </div>
                <div className={styles.item_locale}>
                  <p>{item.usage}</p>
                  <h5>{item.location}</h5>
                  <button>Book an Appointment</button>
                </div>
              </a>
            </Link>
          ))}
        </section>
      </div>
    </div>
  );
}

export const getServerSideProps = async (pageContext) => {
  let data = await axios.get(
    "http://thecarportal.herokuapp.com/automart/carsales/"
  );
  let martInfo = await data.data.message;
  return {
    props: {
      martInfo,
    },
  };
};

export default Carsales;
