import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Carsales.module.css";
import axios from "axios";
import { getNumberWithCommas } from "../utils/functions";
import Link from "next/link";
import Inspection from "../components/Inspection";
import { GiToggles } from "react-icons/gi";

function Carsales({ martInfo }) {
  console.log(martInfo);
  const [id, setId] = useState('')
  const [showIns, setShowIns] = useState(false)
  const [carList, setCarList] = useState(martInfo)

  
  const showDrop = (id) => {
    setShowIns(true)
    setId(id)
  }

  const filterList = (vehicle) => {
    if (vehicle === 'all') {
      setCarList(martInfo)
      return
    }
    let newList = martInfo.filter((car) => {
      if (car.style.toLowerCase() === vehicle) {
          return car
      }
    })
    setCarList(newList)
  }

  return (
    <div>
      <Head>
        <title>CarPotal | Car sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.auto_mart}>
        {showIns && <Inspection toggle={setShowIns} id={id}/>}
        <aside className={styles.mart_side}>
          <div className={styles.mart_menu}>
            <ul>
              <li className={styles.menu_head}>CLASS</li>
              <li onClick={()=>filterList('sedan')}>Sedan</li>
              <li onClick={()=>filterList('suv')}>Suv</li>
              <li onClick={()=>filterList('truck')}>Truck</li>
              <li onClick={()=>filterList('all')}>All Cars</li>
            </ul>
          </div>
        </aside>
        <section className={styles.mart_body}>
          {carList.length == 0 ? 
          <h2 className={styles.collection}>No Cars Available at this moment</h2>
          :
          carList.map((item, i) => (
              <div className={styles.mart_item} key={i}>
                <Link href={`/carsales/${item.id}`}>
                <a className={styles.item_info}>
                    <div className={styles.image}>
                      <img src={item.images[0]} alt="" />
                    </div>
                    <h4>{item.name}<span>{item.model}</span></h4>
                    <h2>
                      {"\u20A6"}
                      {getNumberWithCommas(item.price)}
                    </h2>
                  </a>
                </Link>
                <div className={styles.item_locale}>
                  <p>{item.usage}</p>
                  <h5>{item.location}</h5>
                  <button onClick={(e) => showDrop(item.id)}>Book an Appointment</button>
                </div>
              </div>
         
          ))}
        </section>
      </div>
    </div>
  );
}

export const getServerSideProps = async (pageContext) => {
  try {
    let data = await axios.get(
      "http://thecarportal.herokuapp.com/automart/carsales/"
    );
    let martInfo = await data.data.message;
    return {
      props: {
        martInfo,
      },
    };
  } catch (error) {
    return {
      redirect: {
          destination: '/404',
          permanent: false,
      }
    };
  }
};

export default Carsales;
